version: '3'

services:
  sources-client:
      container_name: sources_client
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /sources_client
      entrypoint:
        - /sources_client/run_server.sh
      environment:
        - DATABASE_NAME=${DATABASE_NAME-sources}
        - DATABASE_USER=${DATABASE_USER-postgres}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD-postgres}
        - POSTGRES_SQL_SERVICE_HOST=sources-db
        - POSTGRES_SQL_SERVICE_PORT=5432
        - SOURCES_KAFKA_TOPIC=${SOURCES_KAFKA_TOPIC-platform.sources.event-stream}

      privileged: true
      ports:
          - 8888:8888
      volumes:
        - '.:/sources_client/'
      links:
        - sources-db
      depends_on:
        - sources-db

  sources-db:
    container_name: sources_db
    image: postgres:9.6
    environment:
    - POSTGRES_DB=${DATABASE_NAME-sources}
    - POSTGRES_USER=${DATABASE_USER-postgres}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD-postgres}
    ports:
      - "15436:5432"
    volumes:
      - ./pg_data:/var/lib/pgsql/data

networks:
  default:
    external:
      name: sources-client-network
